### ISSUE TITLE
Unable to dismiss

### ISSUE THREAD

**Issue by Marcosmaliki** [lcsvcn/speed_dial_fab#1]
The animation is great! Is it possible to expose the controller or a function that can reverse the animation? Something like `controller.reverse()`
Dismissing the child FABs is currently not possible

**Comment by lcsvcn** [comment]
Hi @Marcosmaliki 

I will look into this soon

**Comment by lcsvcn** [comment]
Please take a look into 2.2.1, you can now call the state functions to force expand or force collapse of the widget.
