### ISSUE TITLE
[FEATURE] Support localizations 

### ISSUE THREAD

**Issue by ahmedghaly15** [lcsvcn/speed_dial_fab#12]
When i use ar locale, the secondaryIconsText list doesn't appear very well as in the images below:

![ar-locale](https://github.com/user-attachments/assets/6fd5a589-da0f-4457-a632-41f152262847)
![en-locale](https://github.com/user-attachments/assets/d174ff11-c28a-4d1d-91bf-a248d8e3af1d)

**Comment by lcsvcn** [comment]
@ahmedghaly15 merged your PR, thanks for the contribution, I will close this issue. Let me know if still need adjustments
