### ISSUE TITLE
How to add text next to icon

### ISSUE THREAD

**Issue by razfazz** [lcsvcn/speed_dial_fab#4]
first thank you for that great package!

until now i could not figure out how to add a text next to the icon as you showed with the gif you linked

**Comment by renanhiramatsu** [comment]
Me neither. secondaryIconsText seems to be not working.

**Comment by lcsvcn** [comment]
Thank you for reporting.

It is fixed at version [2.2.3](https://github.com/lcsvcn/speed_dial_fab/releases/tag/2.2.3)
